### ISSUE TITLE
Setup symbolic links for files

### ISSUE THREAD

**Issue by s-rafaeldias** [s-rafaeldias/dotfiles#4]
## TODO
- [x] zsh files
- [x] bash files
- [x] neovim/vim settings
- [x] scritp for automation
- [ ] git settings
- [x] tmux settings
- [x] lein profile.clj

**Comment by s-rafaeldias** [comment]
Using stow
